server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8080/eureka/}
  instance:
    instance-id: frontend-instance
spring:
  application:
    name: frontend