server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
#  if you add properties like above, replication will not be happened.
#  Because eureka checks url of service-url and compare it with hostname of itself.
#  if it is url for itself, this node will be excluded for replica nodes
      defaultZone: ${EUREKA_HOST:http://localhost:8080/eureka/}